# Generated by Django 4.0.1 on 2022-01-27 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
    ]
